### ISSUE TITLE
No forecasting in the file for CalCat

### ISSUE THREAD

**Issue by vnminin** [damonbayer/covid_SEIHR_county#17]
It does not look like we are forecasting, because the last date is 10/31/2022 everywhere: https://github.com/damonbayer/covid_SEIHR_county/blob/master/posterior_predictive_LEMMA_format.csv

**Comment by damonbayer** [comment]
I see forecast through 2023-01-23. https://github.com/damonbayer/covid_SEIHR_county/blob/master/posterior_predictive_LEMMA_format.csv#L7903

**Comment by vnminin** [comment]
Oops, you are right, @damonbayer. We used to have estimates and forecasting in consecutive rows together, so I didn't look further down.
